# PLay example

---

- hosts: webservers:loadbalancers
  tasks:
          - name: Check uptime
            register: uptimeoutput
            command: uptime

          - debug:
              var: uptimeoutput.stdout_lines