# Install httpd and php on servers.

---

  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing Apache
        apt:
          name: apache2
          state: present

      - name: Ensure Apache starts
        service: name=apache2 state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing services
        apt:
          pkg:
          - apache2
          - php
          state: present

      - name: Ensure Apache starts
        service: name=apache2 state=started enabled=yes