# Copy application files to webservers.

---
  - hosts: webservers
    become: true
    tasks:
    - name: Copy application files
      copy:
        src: ../index.php
        dest: /var/www/html
        mode: 0755

    - name: Configure php.ini file
      lineinfile:
        path: /etc/php/7.4/apache2/php.ini
        regexp: ^short_open_tag
        line: 'short_open_tag=On'

    - name: restart apache
      service: name=apache2 state=restarted